### ISSUE TITLE
Icewm 1.9.2 does not compile on OpenSuSE Leap 15.1

### ISSUE THREAD

**Issue by hharders** [bbidulock/icewm#516]
Hi,

I have downloaded Icewm 1.9.2 according to https://ice-wm.org/ and tried to compile it. All used libraries are up-to-date versions as provided by OpenSuSE Leap 15.1.

During compiling, I get following error messages:
make[2]: Verzeichnis „/home/harders/download/icewm/icewm-1.9.2/src“ wird betreten
  CXX      ycolor.lo
In file included from yxapp.h:5:0,
                 from ycolor.cc:8:
ywindow.h:233:5: error: ‘XRenderPictFormat’ does not name a type; did you mean ‘BadPictFormat’?
     XRenderPictFormat* format();
     ^~~~~~~~~~~~~~~~~
     BadPictFormat
In file included from ycolor.cc:8:0:
yxapp.h:118:5: error: ‘XRenderPictFormat’ does not name a type; did you mean ‘BadPictFormat’?
     XRenderPictFormat* formatForDepth(unsigned depth) const;
     ^~~~~~~~~~~~~~~~~
     BadPictFormat
yxapp.h:119:5: error: ‘XRenderPictFormat’ does not name a type; did you mean ‘BadPictFormat’?
     XRenderPictFormat* format() const { return formatForDepth(fDepth); }
     ^~~~~~~~~~~~~~~~~
     BadPictFormat
yxapp.h:182:5: error: ‘XRenderPictFormat’ does not name a type; did you mean ‘BadPictFormat’?
     XRenderPictFormat* findFormat(int depth) const;
     ^~~~~~~~~~~~~~~~~
     BadPictFormat
yxapp.h:189:5: error: ‘XRenderPictFormat’ does not name a type; did you mean ‘BadPictFormat’?
     XRenderPictFormat* fFormat32;
     ^~~~~~~~~~~~~~~~~
     BadPictFormat
yxapp.h:190:5: error: ‘XRenderPictFormat’ does not name a type; did you mean ‘BadPictFormat’?
     XRenderPictFormat* fFormat24;
     ^~~~~~~~~~~~~~~~~
     BadPictFormat
make[2]: *** [Makefile:1541: ycolor.lo] Fehler 1
make[2]: Verzeichnis „/home/harders/download/icewm/icewm-1.9.2/src“ wird verlassen
make[1]: *** [Makefile:593: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/harders/download/icewm/icewm-1.9.2“ wird verlassen
make: *** [Makefile:475: all] Fehler 2

Please let me know which additional information you need to help me resolving the issue.

Best regards
Harald
[config.log](https://github.com/bbidulock/icewm/files/5542244/config.log)

**Comment by Code7R** [comment]
That's strange, those types are defined in Xrender.h which is always included. Please check the contents of /usr/include/X11/extensions/Xrender.h .

Also please build like: make V=1

Alternatively, you could try the cmake build system (see INSTALL.cmake, and "make VERBOSE=1"). This is probably not a fix but might reveal more details.

**Comment by hharders** [comment]
Xrender.h contains a typedef struct { ... } XRenderPictFormat. So it should be existing.

make V=1 does not change anything.

Using cmake makes the error message much more verbose. However, it is basically the same:
```
In file included from /home/harders/download/icewm/icewm-1.9.2/src/yxapp.h:5:0,
                 from /home/harders/download/icewm/icewm-1.9.2/src/yxapp.cc:2:
/home/harders/download/icewm/icewm-1.9.2/src/ywindow.h:233:5: error: ‘XRenderPictFormat’ does not name a type; did you mean ‘BadPictFormat’?
     XRenderPictFormat* format();
     ^~~~~~~~~~~~~~~~~
     BadPictFormat
...
```
I've checked. There's only one Xrender.h below /usr. So I don't know what's the issue.

However, if I'm the only one having this issue, we might want to forget about fixing it. Somebody in the German OpenSUSE forum (Sauerland) has generated a repository for me containing the IceWM 1.9.2 version. This way I don't have to compile the window manager myself anymore.

Thank you very much for the quick answer, Code7R!

**Comment by Code7R** [comment]
If you think so then you can close this issue, feel free.

I, for one, would still prefer to understand it.
And do something like,

a) posting the actual compiler command line from the build log
b) add -E option to it and rename ycolor.o (or ycolor.lo) to ycolor.txt

And then post the ycolor.txt file here, for further investigation.

**Comment by gijsbers** [comment]
Please post the output of `icewm-1.9.2/rebuild.sh -d`.
Is your system up-to-date with the latest system patches?

**Comment by hharders** [comment]
I'm not sure what the build log is you're talking about.
In config.log, I found following row: `CXX='g++'`. Is this, what you mean?

When calling `CXX="g++ -E" ./configure --prefix=/usr`, the configure script does not run through but complains as follows: `configure: error: Need C++11. Please set CXXFLAGS`.
How's the best way to add `-E` to the compiler command?

Yes, my system is up to date.
Output of `rebuild.sh -d` is:
```
x11                 : 1.6.5
xext                : 1.3.3
xcomposite          : 0.4.4
xdamage             : 1.1.4
xfixes              : 5.0.3
xrender             : 0.9.10
xrandr              : Package xrandr was not found in the pkg-config search path.
Perhaps you should add the directory containing `xrandr.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xrandr' found
xinerama            : Package xinerama was not found in the pkg-config search path.
Perhaps you should add the directory containing `xinerama.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xinerama' found
xft                 : Package xft was not found in the pkg-config search path.
Perhaps you should add the directory containing `xft.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xft' found
fontconfig          : 2.13.1
sm                  : Package sm was not found in the pkg-config search path.
Perhaps you should add the directory containing `sm.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sm' found
ice                 : Package ice was not found in the pkg-config search path.
Perhaps you should add the directory containing `ice.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ice' found
sndfile             : Package sndfile was not found in the pkg-config search path.
Perhaps you should add the directory containing `sndfile.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sndfile' found
alsa                : Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
No package 'alsa' found
ao                  : Package ao was not found in the pkg-config search path.
Perhaps you should add the directory containing `ao.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ao' found
gio-2.0             : 2.54.3
gio-unix-2.0        : 2.54.3
gdk-pixbuf-xlib-2.0 : 2.36.10
librsvg-2.0         : Package librsvg-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `librsvg-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'librsvg-2.0' found
xpm                 : 3.5.12
libpng              : Package libpng was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpng.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpng' found
libjpeg             : Package libjpeg was not found in the pkg-config search path.
Perhaps you should add the directory containing `libjpeg.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libjpeg' found`
```
Looks like a lot of stuff is missing. Is this correct? Why does configure.sh not complain then?
Should I install all libraries `rebuild.sh` is missing?

**Comment by hharders** [comment]
Sorry for messing up with formatting!

**Comment by hharders** [comment]
I have installed all packages rebuild.sh was complaining about. Now it's output is:
```
x11                 : 1.6.5
xext                : 1.3.3
xcomposite          : 0.4.4
xdamage             : 1.1.4
xfixes              : 5.0.3
xrender             : 0.9.10
xrandr              : 1.5.1
xinerama            : 1.1.3
xft                 : 2.3.2
fontconfig          : 2.13.1
sm                  : 1.2.2
ice                 : 1.0.9
sndfile             : 1.0.28
alsa                : 1.2.4
ao                  : 1.2.2
gio-2.0             : 2.54.3
gio-unix-2.0        : 2.54.3
gdk-pixbuf-xlib-2.0 : 2.36.10
librsvg-2.0         : 2.42.8
xpm                 : 3.5.12
libpng              : 1.6.37
libjpeg             : 2.0.5
```
Compiling using `make` completes fine, now.
Looks like the checks of `configure` are incomplete and
should result in an error message if a mandatory package is missing.
Does this fit to your conclusions?

**Comment by gijsbers** [comment]
Thanks for your updates to this issue.
configure.ac does have this line:
`PKG_CHECK_MODULES([CORE],[fontconfig xrender xcomposite xdamage xfixes xext x11])`.
So a number of packages are being tested.

We now allow the xrandr, xinerama, shape and xft packages to be optional.
When users simply forgot to install them they get unintended results.
It would therefore be more foolproof if we simply required these four packages.
That is my proposal for a change:
make xrandr, xinerama, shape and xft required dependencies for icewm.
