### ISSUE TITLE
icewm-1-3-BRANCH: Won't compile with enable-guievents enabled

### ISSUE THREAD

**Issue by DeltaResero** [bbidulock/icewm#1]
Any attempts to compile on the 1.3 branch with GUI events enabled will result in the following error:

wmmgr.cc: In member function ‘void YWindowManager::activateWorkspace(long int)’:
wmmgr.cc:2370:9: error: ‘wmapp’ was not declared in this scope
         wmapp->signalGuiEvent(geWorkspaceChange);
         ^
wmmgr.cc: In member function ‘void YWindowManager::checkLogout()’:
wmmgr.cc:2995:34: warning: ignoring return value of ‘int system(const char_)’, declared with attribute warn_unused_result [-Wunused-result]
             system(rebootCommand);
                                  ^
wmmgr.cc:2998:36: warning: ignoring return value of ‘int system(const char_)’, declared with attribute warn_unused_result [-Wunused-result]
             system(shutdownCommand);
                                    ^
make[1]: **\* [wmmgr.o] Error 1
make[1]: Leaving directory `.../icewm/src'
make: **\* [base] Error 2

It seems this bug was mentioned too on Sourceforge but was never fixed: http://sourceforge.net/p/icewm/bugs/910/

**Comment by bbidulock** [comment]
Looking at the code, that option hasn't compiled since before 2002 (before 1.2.0) and I seriously question whether it ever compiled on 1-2-BRANCH or 1-3-BRANCH.  Perhaps it compiled before the code was placed under git (1.1.x or some such).  wmapp never existed in these objects.  Perhaps it was a global that was removed.  Do you know of a version on which it ever compiled?

**Comment by bbidulock** [comment]
Ok. wmapp was a global. Commit 339dfe70 removed it.  I'll see if I can add it back when CONFIG_GUIEVENTS is defined.

**Comment by DeltaResero** [comment]
I'm assuming it did compile at one point in time, but using git bisect is nearly useless as there are a lot of other bugs along the way that intertwine with other features downstream.  I'd like to have this running again, but it seems this is beyond what I can currently do (I'm not as familiar with C++ as I am with C).  I'm curious to see if the ALSA sound patch will still work with it.  I modified the version that was posted here: http://sourceforge.net/p/icewm/patches/157/ ).

**Comment by DeltaResero** [comment]
Wow, I knew the issue was with either wmmgr.cc or it's header, but I never though it was this simple;  It seems I should have just done what the compiler was asking for.  If it would have been a snake it would have bit me; good thing it's not [Python](http://www.python.org/).  Thanks for fixing this so quick.  I'm going to close this issue as the GUI events seems to finally compile again.  I wonder why this never got fixed in the CVS version, surely someone else would have noticed it before now.
